development:
  adapter: postgresql
  database: b7bevba6yltod3ow77yn
  username: u9rp7xix7mlnvostnqbv
  password: hAXFtl5ZsR6OvCIttLH5
  host: b7bevba6yltod3ow77yn-postgresql.services.clever-cloud.com
  port: 6913
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: postgresql
  database: b7bevba6yltod3ow77yn
  username: u9rp7xix7mlnvostnqbv
  password: hAXFtl5ZsR6OvCIttLH5
  host: b7bevba6yltod3ow77yn-postgresql.services.clever-cloud.com
  port: 6913
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
