default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  sportworld
  password: 123456
  host: localhost

development:
  <<: *default
  database: sport_development

test:
  <<: *default
  database: sport_test

production:
  <<: *default
  database: sport_production
  username: sportworld
  password: <%= ENV['123456'] %>

